version: "3"

services:
  feodev-db:
    image: postgres:14.5-alpine
    env_file: ../.env
    volumes:
      - feodev-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  feodev-db-volume:
